<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="44" started-at="2018-07-25T11:41:55Z" finished-at="2018-07-25T11:41:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44" started-at="2018-07-25T11:41:55Z" finished-at="2018-07-25T11:41:55Z">
      <class name="com.scp.TestNG.CTest">
        <test-method status="PASS" signature="cTest2()[pri:0, instance:com.scp.TestNG.CTest@17e2f02]" name="cTest2" is-config="true" duration-ms="12" started-at="2018-07-25T17:11:55Z" finished-at="2018-07-25T17:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cTest2 -->
        <test-method status="PASS" signature="cTest1()[pri:0, instance:com.scp.TestNG.CTest@17e2f02]" name="cTest1" duration-ms="6" started-at="2018-07-25T17:11:55Z" finished-at="2018-07-25T17:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cTest1 -->
      </class> <!-- com.scp.TestNG.CTest -->
      <class name="com.scp.TestNG.DTest">
        <test-method status="FAIL" signature="dTest2()[pri:0, instance:com.scp.TestNG.DTest@7fa833]" name="dTest2" duration-ms="4" started-at="2018-07-25T17:11:55Z" finished-at="2018-07-25T17:11:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.scp.TestNG.DTest.dTest2(DTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dTest2 -->
        <test-method status="SKIP" signature="dTest1()[pri:0, instance:com.scp.TestNG.DTest@7fa833]" name="dTest1" duration-ms="0" started-at="2018-07-25T17:11:55Z" depends-on-methods="com.scp.TestNG.DTest.dTest2" finished-at="2018-07-25T17:11:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DTest.dTest1()[pri:0, instance:com.scp.TestNG.DTest@7fa833] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DTest.dTest1()[pri:0, instance:com.scp.TestNG.DTest@7fa833] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dTest1 -->
      </class> <!-- com.scp.TestNG.DTest -->
      <class name="com.scp.TestNG.ATest">
        <test-method status="FAIL" signature="A()[pri:0, instance:com.scp.TestNG.ATest@1aeed2f]" name="A" duration-ms="1" started-at="2018-07-25T17:11:55Z" finished-at="2018-07-25T17:11:55Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at com.scp.TestNG.ATest.A(ATest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A -->
        <test-method status="PASS" signature="A1()[pri:0, instance:com.scp.TestNG.ATest@1aeed2f]" name="A1" duration-ms="1" started-at="2018-07-25T17:11:55Z" finished-at="2018-07-25T17:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- A1 -->
      </class> <!-- com.scp.TestNG.ATest -->
      <class name="com.scp.TestNG.BTest">
        <test-method status="PASS" signature="B()[pri:0, instance:com.scp.TestNG.BTest@4af044]" name="B" duration-ms="1" started-at="2018-07-25T17:11:55Z" finished-at="2018-07-25T17:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B -->
        <test-method status="PASS" signature="B1()[pri:0, instance:com.scp.TestNG.BTest@4af044]" name="B1" duration-ms="2" started-at="2018-07-25T17:11:55Z" finished-at="2018-07-25T17:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B1 -->
      </class> <!-- com.scp.TestNG.BTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
